# Generated by Django 2.0.5 on 2018-05-17 09:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='recipients',
            field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Recipients'),
        ),
    ]
